### PR TITLE
Fixed meson libtcc build

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
I just added one source file and that was enough to get it to finish linking. Was there something else more significant that needed to be done with this?

**Comment by KaruroChori** [comment]
No, thank you for your help! I just tested it as a subproject and it is working as expected.
I noticed you also extended support for the github workflow, it is really appreciated.

Something which I find strange is to use the latest ubuntu image, for firefox to be (rightfully) removed and upgraded.
Wouldn't a more lightweight alternative based on a rolling release be better in this case? I will perform some tests with that :).

**Comment by KaruroChori** [comment]
Since you asked, I opened [this issue](https://github.com/KaruroChori/tcc-vs/issues/4https://github.com/KaruroChori/tcc-vs/issues/4) to track what would be needed to reach feature parity with the makefile beyond my specific needs, and what I think would be needed to add upstream tinycc in wrap-db.

**Comment by andy5995** [comment]
> Something which I find strange is to use the latest ubuntu image, for firefox to be (rightfully) removed and upgraded. Wouldn't a more lightweight alternative based on a rolling release be better in this case? I will perform some tests with that :).

Yes, no, and depends. ;)

The [GitHub runner images](https://github.com/actions/runner-images) are updated periodically. I believe I believe -latest redirects to 22.04 right now, although 24.04 is available if specified.

I would say you are correct that a light-weight alternative could be considered for this project. As far as I know, that would simply involve adding a dockerfile and workflow that periodically pushes the image. I do that for one of my other projects, but for testing on other distros:

https://github.com/theimpossibleastronaut/rmw/blob/master/.github/workflows/docker-build-env.yml
https://github.com/theimpossibleastronaut/rmw/blob/master/.github/workflows/c-cpp.yml

It probably would be a good solution to have a single dedicated rolling ubuntu image that could be used for different projects.

**Comment by KaruroChori** [comment]
> The [GitHub runner images](https://github.com/actions/runner-images) are updated periodically. I believe I believe -latest redirects to 22.04 right now, although 24.04 is available if specified.

It seems like that is the case. It is shipping an ancient version of meson, so I will be changing it to 24.04 for now.
And thank you for your suggestion, I will be reading more about that, as it can be useful in few other projects of mine.

**Comment by andy5995** [comment]
> > The [GitHub runner images](https://github.com/actions/runner-images) are updated periodically. I believe I believe -latest redirects to 22.04 right now, although 24.04 is available if specified.
> 

I install meson with pip if the version of Ubuntu doesn't include the minimum version of meson I need. Ubuntu 20.04 is supported until April of 2025 so I still test my main projects on that version.

I don't have a recommendation here though, I just wanted to share one point of view in case you find it useful. :)

**Pull request merged**
